# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created', '-updated')},
        ),
    ]
