# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-09 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180307_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', redactor.fields.RedactorField(verbose_name='Text')),
                ('available', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created', '-updated'),
            },
        ),
        migrations.CreateModel(
            name='VisiMisi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', redactor.fields.RedactorField(verbose_name='Text')),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=redactor.fields.RedactorField(verbose_name='Text'),
        ),
    ]
