# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-09 04:35
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wisata', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisiMisi',
        ),
        migrations.AlterField(
            model_name='wisata',
            name='content',
            field=redactor.fields.RedactorField(verbose_name='Text'),
        ),
    ]
