# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-09 04:35
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='link',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
